@extends('layouts.fitmeal')

@section('content')
</div>
        <div class="container main-wrapper"></div>
        <header class="page-header ltx-header-narrow-wrapper">
            <div class="container">
                <div class="ltx-narrow-header"><span class="ltx-cats"><a href="http://fitmeal.like-themes.com/category/nutritionist/">Nutritionist</a></span>
                    <h1 class="header ltx-check-scroll ltx-glitch" data-text="How many calories an adult needs per day">How many calories an adult needs per day</h1>
                    <div class="ltx-post-headline"><a href="http://fitmeal.like-themes.com/how-many-calories-an-adult-needs-per-day/" class="ltx-date"><span>December 12, 2018</span></a><a href="http://fitmeal.like-themes.com/how-many-calories-an-adult-needs-per-day/" class="ltx-comments"><span>2 Comments</span></a></div>
                </div>
            </div>
        </header>
        <div class="container main-wrapper">
            <div class="inner-page margin-post">
                <div class="row row-center">
                    <div class="col-xl-8 col-lg-10 col-md-12 col-xs-12">
                        <section class="blog-post">
                            <article id="post-6578" class="post-6578 post type-post status-publish format-standard has-post-thumbnail hentry category-nutritionist category-vegetarian tag-nutrition">
                                <div class="entry-content clearfix" id="entry-div">
                                    <div class="image"><img width="1600" height="1077" src="http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_02.jpg" class="attachment-fitmeal-post size-fitmeal-post wp-post-image" alt="" srcset="http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_02.jpg 1600w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_02-300x202.jpg 300w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_02-768x517.jpg 768w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_02-1024x689.jpg 1024w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_02-1536x1034.jpg 1536w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_02-360x242.jpg 360w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_02-600x404.jpg 600w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_02-800x539.jpg 800w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_02-550x370.jpg 550w" sizes="(max-width: 1600px) 100vw, 1600px" /></div>
                                    <div class="ltx-description">
                                        <div class="text text-page">
                                            <p>Morbi volutpat nisi a ligula vestibulum placerat. Suspendisse venenatis pulvinar nibh sed convallis. Cras elementum nunc a purus sodales tincidunt. Duis fringilla quam at tellus consectetur, id placerat metus tincidunt. In tellus mauris, pellentesque ac est sed, vestibulum hendrerit felis. Pellentesque molestie lorem id placerat condimentum. Integer fermentum arcu at massa vestibulum placerat. Donec placerat suscipit sollicitudin. Nam pretium est sit amet urna semper ullamcorper. Nulla facilisi. Sed pellentesque tempor tempor. Vestibulum tristique pellentesque feugiat. Vivamus in nisl nec quam maximus venenatis. Sed euismod eros bibendum, dignissim erat sed, blandit tellus.</p>
                                            <p>Pellentesque vehicula, erat eu ullamcorper aliquam, nisi sapien tincidunt erat, vel mollis leo metus a velit. In posuere tempor ante, non gravida lectus. Sed luctus, lectus non rutrum ornare, mi ipsum dignissim neque, a hendrerit tellus risus id elit. Suspendisse tincidunt rhoncus condimentum. Donec nunc velit, rutrum a leo et, lacinia tincidunt tortor. Nulla rhoncus sollicitudin lectus, at facilisis mi consequat pretium. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce porttitor nulla orci, gravida aliquam nisl porttitor eget. Donec eget consectetur mi. Sed a nunc porttitor turpis vulputate rutrum. Phasellus at aliquam elit.</p>
                                            <blockquote class="wp-block-quote">
                                                <p> Vivamus tristique ligula quis orci malesuada tincidunt. Praesent magna purus, pharetra eu eleifend non, euismod vitae leo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque sapien enim, feugiat et mi vel, fermentum placerat tortor.</p><cite> Mallory Mcdaniel </cite></blockquote>
                                            <h3> Health and Fitness</h3>
                                            <p> Morbi volutpat nisi a ligula vestibulum placerat. Suspendisse venenatis pulvinar nibh sed convallis. Cras elementum nunc a purus sodales tincidunt. Duis fringilla quam at tellus consectetur, id placerat metus tincidunt. In tellus mauris, pellentesque ac est sed, vestibulum hendrerit felis. Pellentesque molestie lorem id placerat condimentum. Integer fermentum arcu at massa vestibulum placerat. Donec placerat suscipit sollicitudin. Nam pretium est sit amet urna semper ullamcorper. Nulla facilisi. Sed pellentesque tempor tempor. Vestibulum tristique pellentesque feugiat. Vivamus in nisl nec quam maximus venenatis. Sed euismod eros bibendum, dignissim erat sed, blandit tellus.</p>
                                            <ul class="check">
                                                <li>Vestibulum iaculis velit</li>
                                                <li>Nec ante varius tempus</li>
                                                <li>Duis sollicitudin lacus sapien</li>
                                                <li>Sed pharetra felis facilisis sed</li>
                                            </ul>
                                            <p> Pellentesque vehicula, erat eu ullamcorper aliquam, nisi sapien tincidunt erat, vel mollis leo metus a velit. In posuere tempor ante, non gravida lectus. Sed luctus, lectus non rutrum ornare, mi ipsum dignissim neque.</p>
                                            <h3> 5 Things You Didn’t Know Health</h3>
                                            <p>Quisque scelerisque suscipit purus, nec venenatis nulla lobortis eu. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse tempor id lacus in tincidunt. Vestibulum porttitor risus diam, nec ullamcorper leo consectetur luctus. Praesent neque nisi, eleifend sed diam sed, ultrices venenatis ipsum. Vestibulum ut sem urna. Mauris lorem neque, egestas eget arcu sit amet, sagittis dictum risus. Sed dolor ligula, dictum ac mattis nec, sagittis non ipsum. Integer sollicitudin nunc vitae nisi facilisis, sed rutrum elit vestibulum. Duis viverra maximus felis at condimentum. Sed congue mi vel massa laoreet, vel laoreet risus sollicitudin. Ut pellentesque est lectus, vitae sodales velit tempus eget. Aenean sem quam, malesuada non venenatis non, porta et magna. Donec nec urna eget sapien ornare tristique. Quisque ac accumsan leo. Curabitur elementum ligula in libero dictum, eu placerat lacus posuere.</p>
                                            <figure class="wp-block-image"><img src="http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_12-1024x683.jpg" alt="" class="wp-image-10881" srcset="http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_12-1024x683.jpg 1024w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_12-300x200.jpg 300w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_12-768x512.jpg 768w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_12-1536x1024.jpg 1536w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_12-360x240.jpg 360w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_12-600x400.jpg 600w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_12-128x84.jpg 128w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_12-800x534.jpg 800w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_12-550x367.jpg 550w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_12.jpg 1600w" sizes="(max-width: 1024px) 100vw, 1024px" /></figure>
                                            <p>Nunc placerat dignissim orci, quis auctor ligula ornare non. Morbi nec augue dui. Etiam convallis dui a elit pretium tristique. Phasellus eros tortor, malesuada sed sagittis sit amet, vestibulum in sem. Vivamus elementum et est in mollis. Pellentesque pretium turpis sit amet augue facilisis porttitor. Quisque laoreet neque luctus, gravida eros sit amet, ornare sapien. Phasellus mollis mi id auctor eleifend. Aliquam erat volutpat. Quisque in elit non nisl hendrerit semper. Mauris tristique nisi vitae lacinia tincidunt.</p>
                                            <h3>Fitness news, articles and information</h3>
                                            <p> Praesent euismod felis quis suscipit fermentum. Nam facilisis nunc at purus laoreet, in mollis magna volutpat. Maecenas posuere, quam vitae sollicitudin viverra, eros mauris ultricies massa, et bibendum arcu felis sed tortor. Duis arcu orci, posuere viverra ultrices vitae, sagittis vel dolor. Vivamus varius pellentesque fermentum. Nunc a nulla mollis, aliquam est non, condimentum nibh. Nam vitae laoreet elit. Quisque pellentesque feugiat aliquam. Phasellus faucibus euismod mauris, in feugiat risus finibus pharetra. Nulla id porttitor libero, et pellentesque diam.</p>
                                            <ul class="wp-block-gallery columns-3 is-cropped">
                                                <li class="blocks-gallery-item">
                                                    <figure><img src="http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_17-1024x708.jpg" alt="" data-id="10886" data-link="http://fitmeal.like-themes.com/blog_17/" class="wp-image-10886" srcset="http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_17-1024x708.jpg 1024w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_17-300x208.jpg 300w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_17-768x531.jpg 768w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_17-1536x1063.jpg 1536w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_17-360x249.jpg 360w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_17-600x415.jpg 600w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_17-755x521.jpg 755w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_17-800x554.jpg 800w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_17-550x381.jpg 550w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_17.jpg 1600w" sizes="(max-width: 1024px) 100vw, 1024px" /></figure>
                                                </li>
                                                <li class="blocks-gallery-item">
                                                    <figure><img src="http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_16-1024x683.jpg" alt="" data-id="10885" data-link="http://fitmeal.like-themes.com/blog_16/" class="wp-image-10885" srcset="http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_16-1024x683.jpg 1024w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_16-300x200.jpg 300w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_16-768x512.jpg 768w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_16-1536x1024.jpg 1536w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_16-360x240.jpg 360w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_16-600x400.jpg 600w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_16-128x84.jpg 128w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_16-800x534.jpg 800w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_16-550x367.jpg 550w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_16.jpg 1600w" sizes="(max-width: 1024px) 100vw, 1024px" /></figure>
                                                </li>
                                                <li class="blocks-gallery-item">
                                                    <figure><img src="http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_15-1024x650.jpg" alt="" data-id="10884" data-link="http://fitmeal.like-themes.com/blog_15/" class="wp-image-10884" srcset="http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_15-1024x650.jpg 1024w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_15-300x190.jpg 300w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_15-768x487.jpg 768w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_15-1536x974.jpg 1536w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_15-360x228.jpg 360w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_15-600x381.jpg 600w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_15-800x508.jpg 800w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_15-550x349.jpg 550w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_15.jpg 1600w" sizes="(max-width: 1024px) 100vw, 1024px" /></figure>
                                                </li>
                                            </ul>
                                            <p> Cras eget tincidunt sem. Sed commodo ipsum ut faucibus iaculis. Sed et mauris non purus tincidunt malesuada. Phasellus condimentum est ut interdum bibendum. Phasellus imperdiet placerat nisl, eget semper ex tristique eu. Vivamus porta est nec tellus dictum sollicitudin. Mauris a sagittis leo. Nullam non sagittis quam, sit amet porta risus. Sed nunc neque, fermentum at turpis quis, dapibus mollis lorem. Maecenas nec tristique odio. Vestibulum finibus turpis vel luctus tristique. Morbi non lectus odio. Etiam a placerat leo.</p>
                                            <figure class="wp-block-image"><img src="http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_09-1024x682.jpg" alt="" class="wp-image-10878" srcset="http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_09-1024x682.jpg 1024w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_09-300x200.jpg 300w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_09-768x512.jpg 768w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_09-1536x1023.jpg 1536w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_09-360x240.jpg 360w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_09-600x400.jpg 600w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_09-128x84.jpg 128w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_09-800x533.jpg 800w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_09-550x366.jpg 550w, http://fitmeal.like-themes.com/wp-content/uploads/2018/02/blog_09.jpg 1600w" sizes="(max-width: 1024px) 100vw, 1024px" /></figure>
                                            <p> Duis ornare purus dui, ac pellentesque sapien varius ac. Curabitur luctus interdum arcu a gravida. Pellentesque pretium risus non eros consectetur vehicula egestas quis arcu. Nulla a est massa. Nullam id odio in eros egestas commodo nec eget lorem. Proin auctor bibendum velit, ut dapibus orci laoreet ut. Aliquam bibendum elementum tortor, in pretium enim venenatis sed. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque molestie eu ligula vitae pulvinar. In nisl ipsum, viverra vitae porttitor et, euismod et risus. Nunc efficitur eros sit amet mattis lacinia. Sed at massa consequat, fermentum massa nec, dignissim massa.</p>
                                            <div class="clear"></div>
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>
                                    <div class="blog-info-post-bottom">
                                        <div class="tags-line">
                                            <div class="tags-line-left"><span class="tags"><span class="tags-header">Tags:</span><span class="tags-short"><a href="http://fitmeal.like-themes.com/tag/nutrition/" rel="tag">nutrition</a></span></span>
                                            </div>
                                            <div class="tags-line-right"><span class="ltx-sharing-header"><span class="fa fa-share-alt"></span> <span class="header">Share</span></span>
                                                <ul class="ltx-sharing">
                                                    <li><a href="http://www.facebook.com/sharer.php?u=http://fitmeal.like-themes.com/how-many-calories-an-adult-needs-per-day/"><span class="ltx-social-color fa fa-facebook"></span></a></li>
                                                    <li><a href="https://twitter.com/intent/tweet?link=http://fitmeal.like-themes.com/how-many-calories-an-adult-needs-per-day/&#038;text=How%20many%20calories%20an%20adult%20needs%20per%20day"><span class="ltx-social-color fa fa-twitter"></span></a></li>
                                                    <li><a href="https://plus.google.com/share?url=http://fitmeal.like-themes.com/how-many-calories-an-adult-needs-per-day/"><span class="ltx-social-color fa fa-google-plus"></span></a></li>
                                                    <li><a href="http://www.linkedin.com/shareArticle?mini=true&#038;url=http://fitmeal.like-themes.com/how-many-calories-an-adult-needs-per-day/"><span class="ltx-social-color fa fa-linkedin"></span></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </article>
                        </section>
                    </div>
                </div>
            </div>
        </div>

@endsection

<!-- Dynamic page generated in 2.145 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2020-04-11 18:25:06 -->

<!-- super cache -->
