<!DOCTYPE html>
<html lang="en-US" style="background: white" ng-app="besafe" ng-strict-di> 

<head>
    @include(config("app.views").'.layouts.ecom-head')
</head>

<body class="page-template page-template-page-templates page-template-full-width page-template-page-templatesfull-width-php page page-id-10921 theme-fitmeal woocommerce-no-js tribe-no-js full-width singular paceloader-enabled no-sidebar wpb-js-composer js-comp-ver-6.0.5 vc_responsive">
    @include(config("app.views").'.layouts.ecom-header')
        
    @yield('content')
    
    @include(config("app.views").'.layouts.ecom-footer')
</body>

</html>
<!-- Dynamic page generated in 1.943 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2020-04-10 17:44:54 -->

<!-- super cache -->