@extends(config("app.views").'.layouts.app')

@section('content')
<!-- blog post area start -->
<div class="blog-details ptb--120">
    <div class="container">
        <div class="row">
            <!-- blog details area start -->
            <div class="col-md-12 col-sm-12 col-xs-12"> 
                <div class="blog-info">
              
                    <div class="blog-summery">
                       <h1><strong>T&eacute;rminos y condiciones de uso del sitio</strong></h1>
<p>Versi&oacute;n vigente 30/09/2020</p>
<p>Este contrato describe los t&eacute;rminos y condiciones generales aplicables al uso de los servicios ofrecidos por <strong>Hoovert Arredondo SAS</strong> dentro del sitio www.petworld.net.co, <a href="https://app.petworld.net.co/">https://app.petworld.net.co</a> y la apliacion movil disponible en Android y IOS. Cualquier persona que desee acceder y/o usar el sitio o los servicios podr&aacute; hacerlo sujet&aacute;ndose a los T&eacute;rminos y Condiciones Generales, y todas las dem&aacute;s pol&iacute;ticas presente en este documento.</p>
<p>CUALQUIER PERSONA QUE NO ACEPTE ESTOS T&Eacute;RMINOS Y CONDICIONES DE USO, LOS CUALES TIENEN UN CAR&Aacute;CTER OBLIGATORIO, DEBER&Aacute; ABSTENERSE DE UTILIZAR EL SITIO Y/O LOS SERVICIOS.</p>
<p>El Usuario debe leer, entender y aceptar todas las condiciones establecidas en los T&eacute;rminos y Condiciones Generales y en las Pol&iacute;ticas de Privacidad as&iacute; como en los dem&aacute;s documentos incorporados, previo a su inscripci&oacute;n como Usuario de Pet World.</p>
<h2>01 - Capacidad</h2>
<p>Los Servicios s&oacute;lo est&aacute;n disponibles para personas que tengan capacidad legal para contratar. No podr&aacute;n utilizar los servicios las personas que no tengan esa capacidad, los menores de edad o usuarios que hayan sido suspendidos temporalmente o inhabilitados definitivamente de <strong>Pet World</strong>. Si est&aacute;s inscribiendo un Usuario como Empresa, debes tener capacidad para contratar a nombre de tal entidad y de obligar a la misma en los t&eacute;rminos de este Acuerdo.</p>
<h2>02 - Inscripci&oacute;n</h2>
<p>Es obligatorio completar el formulario de inscripci&oacute;n en todos sus campos con datos v&aacute;lidos para poder utilizar los servicios que ofrece <strong>Pet World</strong>. El futuro Usuario deber&aacute; completarlo con su informaci&oacute;n personal de manera exacta, precisa y verdadera y asume el compromiso de actualizar los Datos Personales conforme resulte necesario.<strong> Hoovert Arredondo SAS.</strong> podr&aacute; utilizar diversos medios para identificar a sus Usuarios, pero NO se responsabiliza por la certeza de los Datos Personales provistos por sus Usuarios. Los Usuarios garantizan y responden, en cualquier caso, de la veracidad, exactitud, vigencia y autenticidad de los Datos Personales ingresados.</p>
<p><strong>Hoovert Arredondo SAS. </strong>podr&aacute; requerir una inscripci&oacute;n adicional a los Usuarios que operen como due&ntilde;os de negocios, como requisito para que dichos Usuarios accedan a la plataforma y herramientas de administraci&oacute;n para la creaci&oacute;n o modificaci&oacute;n de la informaci&oacute;n sobre sus productos o servicios ofrecidos en la plataforma de<strong> Pet World</strong>.</p>
<p><strong>Hoovert Arredondo SAS</strong>. se reserva el derecho de solicitar alg&uacute;n comprobante y/o dato adicional a efectos de corroborar los Datos Personales, as&iacute; como de suspender temporal o definitivamente a aquellos Usuarios cuyos datos no hayan podido ser confirmados. En estos casos de inhabilitaci&oacute;n, se dar&aacute; de baja todos los art&iacute;culos y /o servicios publicados en <strong>Pet World</strong>, as&iacute; como las ofertas realizadas, sin que ello genere alg&uacute;n derecho a resarcimiento.</p>
<p>El Usuario accede a su cuenta personal mediante el ingreso de su usuarios (usuario= correo electr&oacute;nico) y clave de seguridad personal elegida. El Usuario se obliga a mantener la confidencialidad de su Clave de Seguridad.</p>
<p>La Cuenta es personal, &uacute;nica e intransferible, y est&aacute; prohibido que un mismo Usuario inscriba o posea m&aacute;s de una Cuenta. En caso que Mercado Libre detecte distintas Cuentas que contengan datos coincidentes o relacionados, podr&aacute; cancelar, suspender o inhabilitarlas.</p>
<p>El Usuario ser&aacute; responsable por todas las operaciones efectuadas en su Cuenta, pues el acceso a la misma est&aacute; restringido al ingreso y uso de su Clave de Seguridad, de conocimiento exclusivo del Usuario. El Usuario se compromete a notificar a <strong>Hoovert Arredondo SAS</strong> en forma inmediata y por medio id&oacute;neo y fehaciente, cualquier uso no autorizado de su Cuenta, as&iacute; como el ingreso por terceros no autorizados a la misma. Se aclara que est&aacute; prohibida la venta, cesi&oacute;n o transferencia de la Cuenta (incluyendo la reputaci&oacute;n y calificaciones) bajo ning&uacute;n t&iacute;tulo.</p>
<p><strong>Hoovert Arredondo SAS</strong> se reserva el derecho de rechazar cualquier solicitud de inscripci&oacute;n o de cancelar una inscripci&oacute;n previamente aceptada, sin que est&eacute; obligado a comunicar o exponer las razones de su decisi&oacute;n y sin que ello genere alg&uacute;n derecho a indemnizaci&oacute;n o resarcimiento.</p>
<h2>03 - Modificaciones del Acuerdo</h2>
<p><strong>Hoovert Arredondo SAS </strong>modificar los T&eacute;rminos y Condiciones Generales en cualquier momento haciendo p&uacute;blicos en el Sitio los t&eacute;rminos modificados. Todos los t&eacute;rminos modificados entrar&aacute;n en vigor a los 10 (diez) d&iacute;as de su publicaci&oacute;n. Dichas modificaciones ser&aacute;n comunicadas por <strong>Hoovert Arredondo SAS</strong> a los usuarios que en la Configuraci&oacute;n de su Cuenta de <strong>Pet World</strong> hayan indicado que desean recibir notificaciones. Todo usuario que no est&eacute; de acuerdo con las modificaciones efectuadas por Mercado Libre podr&aacute; solicitar la cancelaci&oacute;n de la cuenta.</p>
<p>El uso del sitio y/o sus servicios implica la aceptaci&oacute;n de estos T&eacute;rminos y Condiciones generales de uso.</p>
<h2>04 - Listado de Bienes</h2>
<p><strong>4.1 Utilizaci&oacute;n de M&eacute;todos de Pago. </strong>Al publicar un producto o servicio en <strong>Pet World</strong>, el usuario vendedor acepta la utilizaci&oacute;n de <strong>PayU </strong>como forma disponible para el pago del bien o servicio ofrecido y <em>se obliga a no modificar el precio de venta del bien o servicio publicado en </em><strong><em>Pet World</em></strong><em>. Asimismo, el usuario declara que ha le&iacute;do, comprendido y aceptado los</em><a href="https://legal.payulatam.com/ES/terminos_y_condiciones_comercios.html"><em> T&eacute;rminos y Condiciones</em></a><em> de utilizaci&oacute;n de dicho servicio.</em></p>
<p><strong>4.2 Pago de tarifas de PayU a trav&eacute;s de Hoovert Arredondo SAS</strong> . Al publicar un anuncio en el sitio, el usuario acepta que los pagos de dichas tarifas se procesar&aacute;n a trav&eacute;s de<strong> Hoovert Arredondo SAS.</strong></p>
<p><strong>4.3 Publicaci&oacute;n de bienes y/o servicios. </strong>El Usuario deber&aacute; ofrecer a la venta, los bienes y/o servicios en las categor&iacute;as y subcategor&iacute;as apropiadas. Las publicaciones podr&aacute;n incluir textos descriptivos, gr&aacute;ficos, fotograf&iacute;as y otros contenidos y condiciones pertinentes para la venta del bien o la contrataci&oacute;n del servicio, siempre que no violen ninguna disposici&oacute;n de este acuerdo o dem&aacute;s pol&iacute;ticas de <strong>Hoovert Arredondo SAS</strong>. . El producto ofrecido por el Usuario Vendedor debe ser exactamente descrito en cuanto a sus condiciones y caracter&iacute;sticas relevantes. Se entiende y presume que mediante la inclusi&oacute;n del bien o servicio en<strong> Pet World</strong>, el Usuario acepta que tiene la intenci&oacute;n y el derecho de vender el bien y est&aacute; facultado para ello por su titular y lo tiene disponible para su entrega inmediata o para el plazo especificado en la publicaci&oacute;n. Se establece que los precios de los productos publicados deber&aacute;n ser expresados con IVA incluido cuando corresponda la aplicaci&oacute;n del mismo, y en moneda del curso legal. <strong>Hoovert Arredondo SAS</strong> podr&aacute; remover cualquier publicaci&oacute;n cuyo precio no sea expresado de esta forma para evitar confusiones o malos entendidos en cuanto al precio final del producto. Se deja expresamente establecido que ninguna descripci&oacute;n podr&aacute; contener datos personales o de contacto, tales como, y sin limitarse a, n&uacute;meros telef&oacute;nicos, direcci&oacute;n de e-mail, direcci&oacute;n postal, direcciones de p&aacute;ginas de Internet que contengan datos como los mencionados anteriormente. No podr&aacute; publicitarse otros medios de pagos, distintos de los enunciados por <strong>Hoovert Arredondo SAS. </strong>&nbsp;en la p&aacute;gina de publicaci&oacute;n de art&iacute;culos. En caso que se infrinja cualquiera de las disposiciones establecidas en esta cl&aacute;usula, <strong>Hoovert Arredondo SAS.</strong> podr&aacute; editar el espacio, solicitar al Usuario que lo edite, o dar de baja la publicaci&oacute;n donde se encuentre la infracci&oacute;n.</p>
<p><strong>4.4 Licencia sobre im&aacute;genes, fotograf&iacute;as, marcas e Informaci&oacute;n de Producto. </strong>El usuario autoriza a <strong>Hoovert Arredondo SAS. </strong>a utilizar, publicar, reproducir y/o adaptar las im&aacute;genes y fotograf&iacute;as incluidas en sus publicaciones, su nombre comercial, marcas, frases publicitarias, logos, dise&ntilde;os, dibujos, im&aacute;genes y todo otro signo distintivo que identifique al Usuario y sus productos o servicios (la "Marca") e informaci&oacute;n de sus productos o servicios ("Informaci&oacute;n de Producto"). Ser&aacute; obligaci&oacute;n del Usuario incluir en las publicaciones las im&aacute;genes, fotograf&iacute;as y Marca, as&iacute; como la Informaci&oacute;n de Producto, de manera actualizada, incluyendo aquellas advertencias que sean requeridas por la legislaci&oacute;n aplicable para la venta o publicidad de los productos y servicios . Conforme a lo anterior, <strong>Hoovert Arredondo SAS. </strong>&nbsp;podr&aacute; obtener las im&aacute;genes, fotograf&iacute;as, Marca e Informaci&oacute;n de Producto directamente del Usuario, terceros autorizados por &eacute;ste, o a trav&eacute;s del sitio web del Usuario.</p>
<p>En particular, el Usuario otorga a <strong>Hoovert Arredondo SAS. </strong>&nbsp;una autorizaci&oacute;n gratuita, irrevocable, no exclusiva, internacional y sin l&iacute;mite temporal para usar, publicar, reproducir y/o adaptar las im&aacute;genes, fotograf&iacute;as, la Marca y la Informaci&oacute;n de Producto con el fin de ser usadas en todos los sitios y aplicaciones de <strong>Pet World</strong>, redes sociales y/o en cualquier medio masivo y no masivo de comunicaci&oacute;n, incluyendo sin limitaci&oacute;n, plataformas y cualquier otro medio digital o f&iacute;sico que <strong>Hoovert Arredondo SAS. </strong>&nbsp;considere oportuno o con aquellas otras plataformas o sitios de Internet con los cuales <strong>Hoovert Arredondo SAS. </strong>&nbsp;haya realizado una alianza, para identificar ofertas, clasificar productos, crear cat&aacute;logos, realizar acciones publicitarias y de marketing vinculadas a los servicios de <strong>Hoovert Arredondo SAS. </strong>incluyendo la posibilidad de asociaci&oacute;n con marcas y/o nombres comerciales de terceros, as&iacute; como sublicenciar su uso a terceros, incluyendo, de manera enunciativa, m&aacute;s no limitativa, facultades de uso, publicaci&oacute;n, reproducci&oacute;n y adaptaci&oacute;n de las im&aacute;genes, fotograf&iacute;as, Marca e Informaci&oacute;n de Producto en el marco de las Publicaciones de Cat&aacute;logo.</p>
<p>El Usuario declara y garantiza que es titular o licenciatario de los derechos necesarios sobre las im&aacute;genes, fotograf&iacute;as contenidas en sus publicaciones, sobre las Marcas, as&iacute; como sobre la Informaci&oacute;n de Producto, y que cuenta con los derechos y facultades necesarias para conceder la autorizaci&oacute;n detallada en esta cl&aacute;usula, siendo responsable exclusivo por cualquier infracci&oacute;n a derechos de terceros o por las inconsistencias o inexactitud en la Informaci&oacute;n de Producto.</p>
<p><strong>Hoovert Arredondo SAS. </strong>&nbsp;podr&aacute; eliminar la publicaci&oacute;n de las im&aacute;genes y fotograf&iacute;as, e incluso del bien o servicio, si interpretara, a su exclusivo criterio, que la imagen no cumple con los presentes T&eacute;rminos y Condiciones.&nbsp;</p>
<p><strong>4.5 Art&iacute;culos Prohibidos.</strong> S&oacute;lo podr&aacute;n ser publicados bienes y/o servicios para mascotas, y cuya venta no se encuentre expresamente prohibida por la ley vigente.&nbsp;</p>
<h1>05 - Privacidad de la Informaci&oacute;n</h1>
<p>Para utilizar los Servicios ofrecidos por <strong>Hoovert Arredondo SAS.</strong>, los Usuarios deber&aacute;n facilitar determinados datos de car&aacute;cter personal. Su informaci&oacute;n personal se procesa y almacena en servidores o medios magn&eacute;ticos que mantienen altos est&aacute;ndares de seguridad y protecci&oacute;n tanto f&iacute;sica como tecnol&oacute;gica. Para mayor informaci&oacute;n sobre la privacidad de los Datos Personales y casos en los que ser&aacute; revelada la informaci&oacute;n personal, se pueden consultar nuestras <strong>Pol&iacute;ticas de Privacidad.</strong></p>
<h2>06 - Obligaciones de los Usuarios</h2>
<p><strong>6.1 Obligaciones del Comprador. </strong>El Comprador est&aacute; obligado a completar el proceso de compra a trav&eacute;s de la plataforma<strong> Pet World </strong>(aplicaciones m&oacute;viles o p&aacute;gina web) para que el servicio se preste o para que el producto f&iacute;sico sea entregado.</p>
<p>Al completar el proceso de compra de un bien o servicio el Usuario acepta quedar obligado por las condiciones de venta incluidas en la descripci&oacute;n del art&iacute;culo en la medida en que las mismas no infrinjan las leyes o los T&eacute;rminos y Condiciones Generales y dem&aacute;s pol&iacute;ticas de <strong>Hoovert Arredondo SAS.</strong> La compra es irrevocable salvo en circunstancias excepcionales, tales como que el producto o servicio recibido no corresponda a la descripci&oacute;n publicada en <strong>Pet world</strong>, que exista un claro error o que el vendedor incumpla su oferta.&nbsp;</p>
<p><strong>6.2 Impuestos. </strong>Tal como lo establece la normativa fiscal vigente, el comprador debe exigir factura o ticket al vendedor como comprobante de la operaci&oacute;n.&nbsp;</p>
<p><strong>6.3. Obligaciones del Vendedor.</strong> El Usuario Vendedor debe tener capacidad legal para vender el bien objeto de su oferta. Asimismo, debe cumplir con todas las obligaciones regulatorias pertinentes y contar con los registros, habilitaciones, permisos y/o autorizaciones exigidos por la normativa aplicable para la venta de los bienes y servicios ofrecidos. La cancelaci&oacute;n de una venta por parte del Usuario vendedor impactar&aacute; en su reputaci&oacute;n en la comunidad. Aquel Usuario vendedor que tenga un porcentaje de ventas canceladas igual o superior a 2%, podr&aacute; ser advertido, suspendido y/o inhabilitado por <strong>Hoovert Arredondo SAS. </strong>&nbsp;para continuar operando en el sitio.</p>
<p>Dado que Mercado Libre es un punto de encuentro entre comprador y vendedor y no participa de las operaciones que se realizan entre ellos, el Vendedor ser&aacute; responsable por todas las obligaciones y cargas impositivas que correspondan por la venta de sus art&iacute;culos, sin que pudiera imput&aacute;rsele a <strong>Hoovert Arredondo SAS. </strong>&nbsp;alg&uacute;n tipo de responsabilidad por incumplimientos en tal sentido.</p>
<p>Cuando el Vendedor haya recibido un pedido de alg&uacute;n art&iacute;culo por &eacute;l publicado, deber&aacute; calificar a la contraparte de acuerdo a lo establecido en la<strong> Cl&aacute;usula 14 de estos T&eacute;rminos y Condiciones Generales.</strong></p>
<p>Impuestos. Como se menciona anteriormente, Hoovert Arredondo SAS. s&oacute;lo pone a disposici&oacute;n de los Usuarios un espacio virtual que les permite comunicarse mediante Internet para encontrar una forma de vender o comprar art&iacute;culos y/o servicios.Hoovert Arredondo SAS. no tiene participaci&oacute;n alguna en el proceso de negociaci&oacute;n y perfeccionamiento del contrato definitivo entre las partes. Por eso, <strong>Hoovert Arredondo SAS. </strong>&nbsp;no es responsable por el efectivo cumplimiento de las obligaciones fiscales o impositivas establecidas por la ley vigente.</p>
<p>El vendedor acepta que los compradores podr&aacute;n pedir el cambio o devoluci&oacute;n del producto en un plazo de 1 d&iacute;a desde que recibe el producto, justificando el motivo y entregando pruebas suficientes.</p>
<p>El vendedor deber&aacute; aceptar el cambio o devoluci&oacute;n del producto vendido y deber&aacute; hacerse cargo de los gastos que esto conlleve, incluyendo los costos de env&iacute;o que fueren necesarios.</p>
<h2>07 - Prohibiciones</h2>
<p>Los Usuarios no podr&aacute;n: (a) manipular los precios de los art&iacute;culos; (b) publicar art&iacute;culos id&eacute;nticos en m&aacute;s de una publicaci&oacute;n. (c) publicar o vender art&iacute;culos prohibidos por los T&eacute;rminos y Condiciones Generales, dem&aacute;s pol&iacute;ticas de<strong> Hoovert Arredondo SAS.</strong> o leyes vigentes; (d) insultar o agredir a otros Usuarios; , <strong>(e) (f) (g) (h), (i)&nbsp;</strong></p>
<p>Este tipo de actividades ser&aacute; investigado por Hoovert Arredondo SAS y el infractor podr&aacute; ser sancionado con la suspensi&oacute;n o cancelaci&oacute;n de la oferta e incluso de su registraci&oacute;n como Usuario de <strong>Pet World </strong>y/o de cualquier otra forma que estime pertinente, sin perjuicio de las acciones legales a que pueda dar lugar por la configuraci&oacute;n de delitos o contravenciones o los perjuicios civiles que pueda causar a los Usuarios.</p>
<h2>08 - Violaciones del Sistema o Bases de Datos</h2>
<p>No est&aacute; permitida ninguna acci&oacute;n o uso de dispositivo, software, u otro medio tendiente a interferir en las actividades y operatoria de <strong>Hoovert Arredondo SAS.</strong> com interferir en las ofertas, descripciones, cuentas o bases de datos de <strong>Hoovert Arredondo SAS.</strong> Cualquier intromisi&oacute;n, tentativa o actividad violatoria o contraria a las leyes sobre derecho de propiedad intelectual y/o a las prohibiciones estipuladas en este contrato har&aacute;n pasible a su responsable de las acciones legales pertinentes, y a las sanciones previstas por este acuerdo, as&iacute; como lo har&aacute; responsable de indemnizar los da&ntilde;os ocasionados.</p>
<h2>09 - Sanciones. Suspensi&oacute;n de operaciones</h2>
<p>Sin perjuicio de otras medidas, <strong>Hoovert Arredondo SAS.</strong> advertir, suspender en forma temporal o inhabilitar definitivamente la Cuenta de un Usuario o una publicaci&oacute;n, aplicar una sanci&oacute;n que impacte negativamente en la reputaci&oacute;n de un Usuario, iniciar las acciones que estime pertinentes y/o suspender la prestaci&oacute;n de sus Servicios si (a) se quebrantara alguna ley, o cualquiera de las estipulaciones de los T&eacute;rminos y Condiciones Generales y dem&aacute;s pol&iacute;ticas de <strong>Hoovert Arredondo SAS.</strong>; (b) si incumpliera sus compromisos como Usuario; (c) si se incurriera a criterio de <strong>Hoovert Arredondo SAS.</strong> en conductas o actos dolosos o fraudulentos; (d) no pudiera verificarse la identidad del Usuario o cualquier informaci&oacute;n proporcionada por el mismo fuere err&oacute;nea; (e) <strong>Hoovert Arredondo SAS.</strong> entendiera que las publicaciones u otras acciones pueden ser causa de responsabilidad para el Usuario que las public&oacute;, para Mercado Libre o para los Usuarios. En el caso de la suspensi&oacute;n o inhabilitaci&oacute;n de un Usuario, todos los art&iacute;culos que tuviera publicados ser&aacute;n removidos del sistema. Tambi&eacute;n se remover&aacute;n del sistema las ofertas de compra de bienes ofrecidos en subasta.</p>
<h2>10 - Responsabilidad</h2>
<p><strong>Hoovert Arredondo SAS.</strong> s&oacute;lo pone a disposici&oacute;n de los Usuarios un espacio virtual que les permite ponerse en comunicaci&oacute;n mediante Internet para encontrar una forma de vender o comprar servicios o bienes para mascotas.</p>
<p><strong>Hoovert Arredondo SAS.</strong> no es el propietario de los art&iacute;culos ofrecidos, no tiene posesi&oacute;n de ellos ni los ofrece en venta.</p>
<p><strong>Hoovert Arredondo SAS.</strong> no interviene en el perfeccionamiento de las operaciones realizadas entre los Usuarios ni en las condiciones por ellos estipuladas para las mismas, por ello no ser&aacute; responsable respecto de la existencia, calidad, cantidad, estado, integridad o legitimidad de los bienes ofrecidos, adquiridos o enajenados por los Usuarios, as&iacute; como de la capacidad para contratar de los Usuarios o de la veracidad de los Datos Personales por ellos ingresados. Cada Usuario conoce y acepta ser el exclusivo responsable por los art&iacute;culos que publica para su venta y por las ofertas y/o compras que realiza.</p>
<p>Debido a que <strong>Hoovert Arredondo SAS.</strong> no tiene ninguna participaci&oacute;n durante todo el tiempo en que el art&iacute;culo se publica para la venta, ni en la posterior negociaci&oacute;n y perfeccionamiento del contrato definitivo entre las partes, no ser&aacute; responsable por el efectivo cumplimiento de las obligaciones asumidas por los Usuarios en el perfeccionamiento de la operaci&oacute;n. El Usuario conoce y acepta que al realizar operaciones con otros Usuarios o terceros lo hace bajo su propio riesgo. En ning&uacute;n caso <strong>Hoovert Arredondo SAS.</strong> ser&aacute; responsable por lucro cesante, o por cualquier otro da&ntilde;o y/o perjuicio que haya podido sufrir el Usuario, debido a las operaciones realizadas o no realizadas por art&iacute;culos publicados a trav&eacute;s de<strong> Pet World.</strong></p>
<p><strong>Hoovert Arredondo SAS. </strong>&nbsp;recomienda actuar con prudencia y sentido com&uacute;n al momento de realizar operaciones con otros Usuarios. El Usuario debe tener presentes, adem&aacute;s, los riesgos de contratar con menores o con personas que se valgan de una identidad falsa. <strong>Hoovert Arredondo SAS.</strong> NO ser&aacute; responsable por la realizaci&oacute;n de ofertas y/o operaciones con otros Usuarios basadas en la confianza depositada en el sistema o los Servicios brindados por <strong>Hoovert Arredondo SAS.</strong>.</p>
<p>En caso que uno o m&aacute;s Usuarios o alg&uacute;n tercero inicien cualquier tipo de reclamo o acciones legales contra otro u otros Usuarios, todos y cada uno de los Usuarios involucrados en dichos reclamos o acciones eximen de toda responsabilidad a <strong>Hoovert Arredondo SAS.</strong> y a sus directores, gerentes, empleados, operarios, representantes y apoderados. Los Usuarios tienen un plazo de 60 d&iacute;as desde la compra para iniciar un reclamo contra otro u otros Usuarios. Una vez vencido este plazo, no podr&aacute;n iniciar un reclamo desde el sitio de <strong>Hoovert Arredondo SAS.</strong>.</p>
<p>En virtud que el usuario vendedor tiene la facultad para crear, editar o eliminar contenidos de sus cuenta como descripciones, fotos e im&aacute;genes y precios de su marca, bienes y servicios, se deja aclarado que en ese caso, el usuario ser&aacute; el exclusivo responsable por esa decisi&oacute;n y las consecuencias que pudieran acarrear.&nbsp;</p>
<h2>11 - Alcance de los servicios de Hoovert Arredondo SAS.</h2>
<p>Este acuerdo no crea ning&uacute;n contrato de sociedad, de mandato, de franquicia, o relaci&oacute;n laboral entre <strong>Hoovert Arredondo SAS.</strong> y el Usuario. El Usuario reconoce y acepta que <strong>Hoovert Arredondo SAS.</strong> no tiene control alguno sobre la calidad, seguridad o legalidad de los art&iacute;culos anunciados, la veracidad o exactitud de los anuncios, la capacidad de los Usuarios para vender o comprar art&iacute;culos. <strong>Hoovert Arredondo SAS.</strong> no puede asegurar que un Usuario completar&aacute; una operaci&oacute;n ni podr&aacute; verificar la identidad o Datos Personales ingresados por los Usuarios. <strong>Hoovert Arredondo SAS.</strong> no garantiza la veracidad de la publicidad de terceros que aparezca en el sitio y no ser&aacute; responsable por la correspondencia o contratos que el Usuario celebre con dichos terceros o con otros Usuarios.</p>
<h2>12 - Fallas en el sistema</h2>
<p><strong>Hoovert Arredondo SAS.</strong> no se responsabiliza por cualquier da&ntilde;o, perjuicio o p&eacute;rdida al Usuario causados por fallas en el sistema, en el servidor o en Internet. <strong>Hoovert Arredondo SAS.</strong> tampoco ser&aacute; responsable por cualquier virus que pudiera infectar el equipo del Usuario como consecuencia del acceso, uso o examen de su sitio web o a ra&iacute;z de cualquier transferencia de datos, archivos, im&aacute;genes, textos, o audio contenidos en el mismo. Los Usuarios NO podr&aacute;n imputarle responsabilidad alguna ni exigir pago por lucro cesante, en virtud de perjuicios resultantes de dificultades t&eacute;cnicas o fallas en los sistemas o en Internet. <strong>Hoovert Arredondo SAS.</strong> no garantiza el acceso y uso continuado o ininterrumpido de su sitio. El sistema puede eventualmente no estar disponible debido a dificultades t&eacute;cnicas o fallas de Internet, o por cualquier otra circunstancia ajena a <strong>Hoovert Arredondo SAS.</strong>; en tales casos se procurar&aacute; restablecerlo con la mayor celeridad posible sin que por ello pueda imputarse alg&uacute;n tipo de responsabilidad. MercadoLibre no ser&aacute; responsable por ning&uacute;n error u omisi&oacute;n contenidos en su sitio web.</p>
<h2>13 - Tarifas. Facturaci&oacute;n</h2>
<p>La inscripci&oacute;n en Mercado Libre es gratuita.</p>
<p>El usuario solo deber&aacute; pagar a <strong>Hoovert Arredondo SAS.</strong> un costo por la venta cuando la operaci&oacute;n se concrete. Para el caso correspondiente a las categor&iacute;as destacadas y banner principal , el Usuario deber&aacute; pagar &uacute;nicamente un costo por publicar.</p>
<p>En todos los casos, los cargos var&iacute;an conforme la exposici&oacute;n del anuncio en el Sitio Web.</p>
<p>El Usuario acepta pagar a <strong>Hoovert Arredondo SAS.</strong> los cargos por publicar, vender o por cualquier otro servicio prestado por <strong>Hoovert Arredondo SAS.</strong> que tenga una tarifa vigente. Los pagos se har&aacute;n usando la plataforma de <strong>PayU</strong></p>
<p><strong>Hoovert Arredondo SAS.</strong> se reserva el derecho de modificar, cambiar, agregar, o eliminar las tarifas vigentes, en cualquier momento, lo cual ser&aacute; notificado a los Usuarios, en la forma establecida en la Cl&aacute;usula 3. Sin embargo, <strong>Hoovert Arredondo SAS.</strong> podr&aacute; modificar temporalmente la Pol&iacute;tica de Tarifas y las tarifas por sus servicios por raz&oacute;n de promociones, siendo efectivas estas modificaciones cuando se haga p&uacute;blica la promoci&oacute;n o se realice el anuncio.</p>
<p><strong>Hoovert Arredondo SAS.</strong> se reserva el derecho de tomar las medidas judiciales y extrajudiciales que estime pertinentes para obtener el pago del monto debido.</p>
<p>En caso de haberse facturado cargos que no hubiesen correspondido, el Usuario deber&aacute; comunicarse con nuestro equipo de Atenci&oacute;n al Cliente para resolver dicha cuesti&oacute;n.&nbsp;</p>
<p>A su exclusiva discreci&oacute;n, <strong>Hoovert Arredondo SAS.</strong> podr&aacute; expedir en forma electr&oacute;nica las facturas correspondientes a las comisiones, cargos y dem&aacute;s conceptos originados en el uso de los Servicios por parte de los Usuarios, seg&uacute;n Resoluci&oacute;n 14.465 de 2007 expedida por la DIAN. La aceptaci&oacute;n de los T&eacute;rminos y Condiciones Generales por el Usuario conlleva, entre otras cuestiones, el consentimiento expreso del Usuario a recibir las mencionadas facturas en forma electr&oacute;nica.</p>
<h2>14 - Propiedad intelectual - Licencias - Enlaces</h2>
<p><strong>Hoovert Arredondo SAS </strong>se reservan todos los derechos, incluyendo los derechos de propiedad intelectual e industrial, asociados con los servicios de <strong>Pet World</strong>, sus sitios web, los contenidos de sus pantallas, programas, bases de datos, redes, c&oacute;digos, desarrollo, software, arquitectura, hardware, contenidos, informaci&oacute;n, tecnolog&iacute;a, fases de integraci&oacute;n, funcionalidades, dominios, archivos que permiten al Usuario acceder y crear su Cuenta, herramientas de venta, marcas, patentes, derechos de autor, dise&ntilde;os y modelos industriales, nombres comerciales, entre otros, y declara que est&aacute;n protegidos por leyes nacionales e internacionales vigentes.</p>
<p>En ning&uacute;n caso se entender&aacute; que el Usuario tendr&aacute; alg&uacute;n tipo de derecho sobre los mismos excepto para utilizar el servicio de Pet World conforme a lo previsto en estos T&eacute;rminos y Condiciones. El uso indebido o contrario a la normativa vigente de los derechos de propiedad intelectual e industrial de <strong>Hoovert Arredondo SAS</strong>, as&iacute; como su reproducci&oacute;n total o parcial, queda prohibido, salvo autorizaci&oacute;n expresa y por escrito de <strong>Hoovert Arredondo SAS</strong>.</p>
<p>Los Usuarios tampoco podr&aacute;n comunicar que los productos o servicios que ofrecen son patrocinados, promovidos, producidos, ofrecidos y/o vendidos por <strong>Hoovert Arredondo SAS</strong>y deber&aacute;n abstenerse de realizar cualquier acto que pudiera causar un da&ntilde;o, p&eacute;rdida de reputaci&oacute;n, o disminuci&oacute;n del valor de los derechos de propiedad intelectual e industrial de <strong>Hoovert Arredondo SAS</strong></p>
<p>El sitio puede contener enlaces a sitios web de terceros. En virtud que<strong>Hoovert Arredondo SAS</strong>no tiene control sobre tales sitios, no ser&aacute; responsable por los contenidos, materiales, acciones y/o servicios prestados por los mismos, ni por da&ntilde;os o p&eacute;rdidas ocasionadas por la utilizaci&oacute;n de &eacute;stos, causados directa o indirectamente. La presencia de enlaces a otros sitios web no implica una sociedad, relaci&oacute;n, aprobaci&oacute;n, respaldo de <strong>Hoovert Arredondo SAS</strong> con dichos sitios y sus contenidos.</p>
<h2>16 - Indemnidad</h2>
<p>El Usuario mantendr&aacute; indemne a Hoovert Arredondo SAS, as&iacute; como a sus filiales, empresas controladas y/o controlantes, funcionarios, directivos, sucesores, administradores, representantes y empleados, por cualquier reclamo iniciado por otros Usuarios, terceros o por cualquier Organismo, relacionado con sus actividades en el Sitio, el cumplimiento y/o el incumplimiento de los T&eacute;rminos y Condiciones Generales o dem&aacute;s Pol&iacute;ticas, as&iacute; como respecto de cualquier violaci&oacute;n de leyes o derechos de terceros.</p>
<p>A tal fin, el Usuario faculta a <strong>Hoovert Arredondo SAS</strong> a: i) intervenir y representarlo en dichos reclamos, pudiendo celebrar los acuerdos transaccionales que considere oportunos y que tiendan a evitar mayores costos y/o evitar eventuales contingencias sin limitaci&oacute;n, en su nombre y representaci&oacute;n; ii) retener la comisi&oacute;n por la venta correspondiente para <strong>Hoovert Arredondo SAS.</strong></p>
<h2>17 - Anexos</h2>
<p>Forman parte integral e inseparable de los T&eacute;rminos y Condiciones Generales, los siguientes documentos y/o secciones de<strong> Hoovert Arredondo SAS</strong> incorporados por referencia, donde se detallan pol&iacute;ticas y/o T&eacute;rminos y Condiciones de diferentes servicios ofrecidos en el sitio. Los mismos se podr&aacute;n consultar dentro del sitio mediante el enlace abajo provisto o accediendo directamente a las p&aacute;ginas correspondientes:</p>
<ul>
<li><a href="https://www.mercadolibre.com.co/ayuda/Politicas-de-privacidad_993">Pol&iacute;tica de privacidad</a></li>
<li><a href="http://ayuda.mercadolibre.com.co/ayuda/terminos-mercado-puntos_3196">T&eacute;rminos y condiciones de </a>PayU</li>
</ul>
<h2>18 - Jurisdicci&oacute;n y Ley Aplicable</h2>
<p>Este acuerdo estar&aacute; regido en todos sus puntos por las leyes vigentes en la Rep&uacute;blica de Colombia.</p>
<p>Cualquier controversia derivada del presente acuerdo, su existencia, validez, interpretaci&oacute;n, alcance o cumplimiento, ser&aacute; sometida a las leyes aplicables y a los Tribunales competentes de la Ciudad de Bogot&aacute; y los procedimientos se llevar&aacute;n a cabo en idioma castellano.</p>
<h2>19 - Domicilio</h2>
<p>Se fija como domicilio de <strong>Hoovert Arredondo SAS</strong> LTDA., con NIT901.219.085-6, en la Carrera 1 este #72A 90 , Bogot&aacute; D.C., Colombia. Tel&eacute;fono (1) 310 3418432</p>
<p>Si tienes alguna duda sobre los T&eacute;rminos y Condiciones Generales o dem&aacute;s pol&iacute;ticas y principios que rigen Hoovert Arredondo SAS comuniucarse via coorreo electronico a <a href="mailto:camilasaca82@gmail.com">camilasaca82@gmail.com</a></p>
                    </div>
                </div>
            </div>
            <!-- blog details area end -->
        </div>
    </div>
</div>
<!-- blog post area end -->
@endsection